# Generated by Django 2.2.2 on 2019-06-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarRent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDes',
            new_name='Car',
        ),
    ]
