# Generated by Django 2.2.2 on 2019-06-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRent', '0002_auto_20190605_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cars/%Y/%m/%d'),
        ),
    ]
