# Generated by Django 2.2.2 on 2019-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRent', '0003_auto_20190606_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='TransmissionType',
        ),
        migrations.AddField(
            model_name='car',
            name='car_Type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('SUV', 'SUV'), ('Mini SUV', 'Mini SUV')], default='SUV', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_Type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='Diesel', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Manual', max_length=10),
            preserve_default=False,
        ),
    ]
