# Generated by Django 2.2.2 on 2019-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRent', '0005_auto_20190606_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('price', 'name')},
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
