# Generated by Django 2.2.2 on 2019-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRent', '0006_auto_20190606_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
